Repository JulioJohan/Social-Hub-Frontend, pull requests merged in 2023-07, with the labels that each got.

#23 Mapeo de servicios de publicaciones
  src/app/models/post.model.ts
  src/app/models/post.modelDTO.ts
  src/app/models/response.model.ts
  src/app/service/publicaciones.service.ts
Labels: enhancement

#24 agregando alertas para el usuario
  src/app/service/alerts.service.ts
Labels: enhancement

#27 Finalizando la conexión de los endpoints del backend
  src/app/authentication/authentication.module.ts
  src/app/pages/Dialog/dialog-signin/dialog-signin.component.html
  src/app/pages/auth/auth-routing.module.ts
  src/app/pages/auth/auth.module.ts
  src/app/pages/auth/change-password/change-password.component.html
  src/app/pages/auth/change-password/change-password.component.ts
  src/app/pages/auth/confirm-account/confirm-account.component.html
  src/app/pages/auth/confirm-account/confirm-account.component.scss
  src/app/pages/auth/confirm-account/confirm-account.component.ts
  src/app/pages/auth/recover-password/recover-password.component.html
  src/app/pages/auth/recover-password/recover-password.component.ts
  src/app/pages/auth/signin/signin.component.html
  src/app/pages/auth/signin/signin.component.ts
  src/app/pages/dialogs/dialog-signin/dialog-signin.component.ts
  src/app/service/alerts.service.ts
  src/app/service/login.service.ts
Labels: actualización

#29 Se agrega la funcionalidad y pantalla de publicaciones
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/header/header.component.html
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/facebook/publications/publications.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/app/service/publicaciones.service.ts
Labels: enhancement

#31 Funcionalidad de publicaciones
  src/app/app.component.scss
  src/app/pages/facebook/create-post/create-post.component.html
  src/app/pages/facebook/create-post/create-post.component.scss
  src/app/pages/facebook/create-post/create-post.component.spec.ts
  src/app/pages/facebook/create-post/create-post.component.ts
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/header/header.component.html
  src/app/pages/facebook/header/header.component.scss
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/facebook/publications/publications.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/index.html
Labels: enhancement

#32 Se realiso ajustes en el menu lateral
  src/app/pages/facebook/header/header.component.html
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/home/header/header.component.html
  src/app/pages/home/header/header.component.ts
  src/app/pages/home/home.component.html
  src/app/pages/home/home.component.scss
  src/app/pages/home/home.component.ts
  src/app/pages/home/home.module.ts
Labels: actualización

#33 Agregando la funcionalidad de crear publicaciones
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/models/post.model.ts
  src/app/models/post.modelDTO.ts
  src/app/pages/facebook/create-post/create-post.component.html
  src/app/pages/facebook/create-post/create-post.component.ts
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/facebook/publications/publications.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/app/service/publicaciones.service.ts
  src/app/shared/utils/utils.ts
Labels: actualización

#34 Agregando funcionalidad Crear comentarios
  src/app/models/comment.ts
  src/app/models/commentDTO.ts
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/publications/comments/comments.component.html
  src/app/pages/facebook/publications/comments/comments.component.scss
  src/app/pages/facebook/publications/comments/comments.component.ts
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/facebook/publications/publications.component.ts
  src/app/service/comments.service.ts
Labels: actualización

#35 Editar usuario
  src/app/pages/auth/signin/signin.component.ts
  src/app/pages/dialogs/dialog-signin/dialog-signin.component.ts
  src/app/pages/home/edit-user/edit-user.component.html
  src/app/pages/home/edit-user/edit-user.component.scss
  src/app/pages/home/edit-user/edit-user.component.spec.ts
  src/app/pages/home/edit-user/edit-user.component.ts
  src/app/pages/home/header/header.component.html
  src/app/pages/home/header/header.component.scss
  src/app/pages/home/header/header.component.ts
  src/app/pages/home/home.module.ts
  src/app/service/login.service.ts
  src/styles.scss
Labels: actualización

#36 Crear my posts
  src/app/app-routing.module.ts
  src/app/pages/facebook/facebook-routing.module.ts
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/header/header.component.html
  src/app/pages/facebook/header/header.component.scss
  src/app/pages/facebook/my-publications/my-publications.component.html
  src/app/pages/facebook/my-publications/my-publications.component.scss
  src/app/pages/facebook/my-publications/my-publications.component.spec.ts
  src/app/pages/facebook/my-publications/my-publications.component.ts
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/home/header/header.component.html
  src/app/pages/home/home.module.ts
Labels: actualización

#37 Finalizando funcionalidad comentarios
  src/app/models/comment.ts
  src/app/pages/facebook/publications/comments/comments.component.html
  src/app/pages/facebook/publications/comments/comments.component.scss
  src/app/pages/facebook/publications/comments/comments.component.ts
  src/app/service/comments.service.ts
Labels: actualización

#38 Feature fix publicaciones
  src/app/pages/facebook/create-post/create-post.component.html
  src/app/pages/facebook/create-post/create-post.component.ts
  src/app/pages/facebook/facebook.module.ts
  src/app/pages/facebook/publications/publications.component.html
  src/app/pages/facebook/publications/publications.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/app/pages/home/header/header.component.html
  src/app/service/publicaciones.service.ts
Labels: actualización

#39 DIseño del comentarios terminado
  src/app/pages/facebook/publications/comments/comments.component.html
  src/app/pages/facebook/publications/comments/comments.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/styles.scss
Labels: actualización

#40 diseñotoktik
  src/app/app-routing.module.ts
  src/app/pages/tiktok/header/header.component.spec.ts
  src/app/pages/tiktok/header/headert.component.html
  src/app/pages/tiktok/header/headert.component.scss
  src/app/pages/tiktok/header/headert.component.ts
  src/app/pages/tiktok/publications/publications.component.html
  src/app/pages/tiktok/publications/publications.component.scss
  src/app/pages/tiktok/publications/publications.component.spec.ts
  src/app/pages/tiktok/publications/publications.component.ts
  src/app/pages/tiktok/tiktok-routing.module.ts
  src/app/pages/tiktok/tiktok.component.html
  src/app/pages/tiktok/tiktok.module.ts
  src/styles.scss
Labels: actualización

#42 Correcciones en la edicion de publicaciones
  src/app/pages/facebook/edit-my-post/edit-my-post.component.ts
  src/app/pages/facebook/my-publications/my-publications.component.html
  src/app/pages/facebook/my-publications/my-publications.component.scss
  src/app/pages/facebook/publications/publications.component.scss
  src/app/pages/facebook/publications/publications.component.ts
  src/app/service/publicaciones.service.ts
Labels: bug, actualización

#43 Correcion editar
  src/app/pages/facebook/publications/comments/comments.component.html
  src/app/pages/facebook/publications/comments/comments.component.ts
  src/app/service/comments.service.ts
Labels: bug

#45 Agregando publicaciones de toktik
  src/app/pages/tiktok/create-post/create-post.component.html
  src/app/pages/tiktok/create-post/create-post.component.scss
  src/app/pages/tiktok/create-post/create-post.component.spec.ts
  src/app/pages/tiktok/create-post/create-post.component.ts
  src/app/pages/tiktok/publications/publications.component.html
  src/app/pages/tiktok/publications/publications.component.scss
  src/app/pages/tiktok/publications/publications.component.ts
  src/app/pages/tiktok/tiktok.module.ts
  src/app/service/publicaciones.service.ts
Labels: Creación

#47 Funcionalidad de los comentarios
  src/app/pages/tiktok/comments/comments.component.html
  src/app/pages/tiktok/comments/comments.component.scss
  src/app/pages/tiktok/comments/comments.component.ts
  src/app/pages/tiktok/publications/publications.component.html
  src/app/pages/tiktok/publications/publications.component.ts
Labels: documentation, actualización

#48 posttiktok
  src/app/app-routing.module.ts
  src/app/pages/tiktok/my-publications/my-publications.component.html
  src/app/pages/tiktok/my-publications/my-publications.component.scss
  src/app/pages/tiktok/my-publications/my-publications.component.ts
  src/app/pages/tiktok/publications/publications.component.html
  src/app/pages/tiktok/tiktok-routing.module.ts
  src/app/pages/tiktok/tiktok.module.ts
Labels: actualización
